### ISSUE TITLE
RFC: Course Batches

### ISSUE THREAD

**Issue by anandology** [fossunited/community#10]
Course Batches is a feature in the LMS that allows a group of students learn a course together with the help of some mentors.

A course can have multiple batches and each batch will have multiple students and mentors.

The platform allows all the members of a batch to discuss among themselves. The mentors will be able to see the progress of the students and leave comments on their work.

## Doctypes

**LMS Batch**

```
fields:
- course: the course of the batch
- code: autogeneted primary key
- title: title of the batch
- description: description of the batch
- visibility: public | unlisted | private
- membership: open | restricted | invite_only | closed
- status: active | inactive
- stage: ready | in-progress | completed | cancelled
```

The batch code is autogenerated. The scheme to generate the code is the later sections.

**LMS Batch Membership**
```
fields:
- batch
- member
- member_type: student | mentor | staff
- role: member | admin
```

Admins of a batch will be able to add/invite new members, approve join requests and change the member type or role of any member.

A batch will always have at least one admin.

**LMS Batch Join Request**
TODO

**LMS Batch Invitation**
TODO

**LMS Message**
```
fields:
- batch
- author
- message: markdown
- pinned: boolean
```

## Batch Code generation scheme

Each course will have a 2-letter code and the batch code (or id) will be of the form XXDD where XX is the course code followed by two digits.

For example, the Joy of Programming course will have a code `JP` and the batches of that course will be numbered as `JP01`, `JP02` etc.

## URLs

Course Page: `/courses/the-joy-of-programming`

Discussion Page: `/courses/the-joy-of-programming/JP01/discussion`

## Tasks

- Add `short_code` field to the course doctype
- Add `LMS Batch` doctype [only accessible in the desk] and autogenerate the batch code
- Add `LMS Batch Membership` doctype [adding new memberships only possible from desk]
- Add `LMS Message` doctype [adding new message is only available from desk]
- When the user is member of a batch, add a discussion tab in the course page, showing all messages for that batch
- Add an option to add a new message from the discussion page
- Send email notifications to members on every message
- Allow users to configure the notification settings. The possible options are:
    - email on every message
    - one digest mail per day
    - never

I've not added invitations and request-to-join etc. as they are not immediately required.

## Discussion

When student is part of an active batch, he can't join any other batch in the same course. However, a mentor or a staff can be part of multiple batches. How do we maintain these checks?

**Comment by anandology** [comment]
@pateljannat and @rmehta please review.

**Comment by rmehta** [comment]
Should we call it "Course Batch" or "Course Group" against "LMS Batch". Personally I like to avoid abbreviations.

**Comment by anandology** [comment]
We started using LMS prefix to avoid conflict with the `Course` doctype in the education module of erpnext. In fact, I'm not a big fan of using that prefix.
