### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by pateljannat** [fossunited/community#100]
- [x] Remove all styles
- [ ] Add frappe default styles
- [x] Course outline on the batch home should have clickable links to lessons
- [x] Replace sidebar with. tabs on batches page
- [x] Course link on the batch page
- [x] Learn
- [x] Members
- [x] About (has been removed for now)
- [x] Discussions
- [ ] Progress
- [x] Batch home

**Comment by anandology** [comment]
The course outline may not have clickable links to lesson unless the student has already signed up for the course. If we do it, then there will be issues with showing the exercises. If we decide to show the lessons to everyone, then we need to figure out how to disable submission of the exercises.

**Comment by pateljannat** [comment]
Currently, if the student is enrolled for a course, they get redirected to the batch page from the course page. So having links in the course outline won't make any sense as the student won't get to access the page.

We can add the Course Outline to the batch home page maybe? The links can be clickable there. @anandology can we consider the About section of Batch as the home page?

cc: @rmehta

**Comment by anandology** [comment]
> Currently, if the student is enrolled for a course, they get redirected to the batch page from the course page. So having links in the course outline won't make any sense as the student won't get to access the page.

It makese sense for students who have not yet signed up for the course. 
 
> We can add the Course Outline to the batch home page maybe? The links can be clickable there. @anandology can we consider the About section of Batch as the home page?

We need to do this as well. Again, this is for students who have already signed up. 

We still need to figure out how students who have not yet signed up get a peek into the course contents.
