### ISSUE TITLE
Signup Flow

### ISSUE THREAD

**Issue by anandology** [fossunited/community#110]
## Overview

This issue proposes an alternative flow for signup, overwriting the default signup flow in Frappe.

## The Issues with current flow

The current signup flow of Frappe creates a user account even before the email is validated. While that has no major implications in regular Frappe apps or ERPNext, that doesn't work for community app because the default signup flow autoassigns a username and no other user will be able to pick that username. It is even possible for someone to create a million user accounts blocking most common usernames.

## Required flow for Community App

The following are the requirements for the signup feature in the community app.
- user account should be created only after the email is validated
- the user should pick username at the time of signup

## Simple Implementation

We already have `Invite Request` in the community app and they takes the user to the new-sign-up page only after the email is validated. However there is  a manual step of accepting the invitation. We could marks the Invite Requests as Approved on creation and that would address all the above requirements.

## A better approach

While the above suggested approach works, it may be good idea to integrate it into the login/signup flow. 

We can enable signup and overwrite the signup form and the action.

* login page will have link to signup
* the signup form will have just email field and on submit, it will send an email with a verification code to complete the signup

When user clicks on the link, the user will be taken to a webpage to create an account. It could be same as the new-sign-up page, but with look and feel similar to the signup page.

**Comment by rmehta** [comment]
@anandology 

At this point we don't have a design for this. Push this for later? Does not seem to help in our target to get 500 users next month?

**Comment by anandology** [comment]
> @anandology
> 
> At this point we don't have a design for this. Push this for later? Does not seem to help in our target to get 500 users next month?

It is hard to even make 100 users to join the batches if I don't have this feature. I need this do that coming Monday. 

I want the user to signup on their own and click an invite link to join the session.

The simple implementation that I proposed above just requires couple of lines of code change and everything else is already in place.

**Comment by pateljannat** [comment]
Invite Request will now be Approved automatically after creation.

https://github.com/fossunited/community/pull/128

Closing this issue
