### ISSUE TITLE
Add Quizes in chapters

### ISSUE THREAD

**Issue by pateljannat** [fossunited/community#112]
### As a student, I want to take quizzes that are part of chapters.

- I want to see the quiz and its questions.
- I want to see the number of times I can attempt the quiz.
-  I want to mark the correct option as the answer.
- I want to submit the quiz.
- I want to check my score.
- I want to re-attempt the quiz if possible.
- I want to see the quiz that I complete on my progress page.

### As a course designer, I want to create quizzes as a part of the chapter.

- I want to add questions to a quiz
- I want to add multiple options to each question.
- I want to add the right answer to each question
- I want to add a configuration that determines the number of attempts a student can take.
- 

### As a mentor, I want to see the quizzes submitted by the students.

- I want to see the quiz submitted by the student.
- I want to see the score they got.
- I want to see the number of attempts they took.

## Solution

- A quiz doctype with fields 

1. Title (Data)
2. Maximum Attempts (Int)
3. Questions (Child Table)
4. Passing Score? (Int)

- Fields for the Questions Table

1.  Question (Markdown)
2. Options (Child Table)
3. Question Type (Select) [Single Correct Answer,  Multiple Correct Answers]

- Fields for Options Table

1. Option (Small Text)
2. Is Correct (Check)

- Lessons doctype has a field Lesson Type with an option as Quiz.
- When Lesson Type is selected as Quiz, a field called Quiz would become visible.
- This would be a link field to quiz doctype. A quiz can be selected here.
- Based on lesson type an appropriate view will render for quizzes.

**Comment by anandology** [comment]
Would quizes be part of a chapter or a lesson?

**Comment by anandology** [comment]
Having too many levels of doctypes (Quiz, Question, Answer) may make it very difficult to add or edit a quiz. How about thinking of a simple YAML based markup for writing a quiz? 

```
question: Who is the president of India?
options:
- Narandra Modi
- Rahul Gandhi
- Ramnath Kovid
- Amit Shah
answer: 3
---
question: How do you change the background of web page? 
multiple_answers: true
options:
- Using HTML
- Using Javascript
- Using CSS
- None of the above
```

Both the question and options can be markdown to include images, code snipppets etc.
