### ISSUE TITLE
Show course progress to the students

### ISSUE THREAD

**Issue by anandology** [fossunited/community#114]
Provide a way for a student to see their own progress of the course. 

We could either has a separate progress page or show the progress on the home page itself. The latter option feels like a better way as the student doesn't have to go to a seperate page to see the progress.

Since we already have a course outline, we could display it right there. I propose showing the progress in three levels.
-  show a tick for the completed lesson 
- show a progress bar for each chapter and a tick if the chapter is complete
- show a progress bar for the entite course

The progress bar for the course could be added to the course teaser pages whereever they are displayed.

**Comment by pateljannat** [comment]
### How to consider a chapter as complete? Observations from similar platforms.

1. [Khan Academy](https://www.khanacademy.org/) shows a tick on the lesson as soon as we open the lesson. So it tracks lesson progress based on the lesson visitation.
2. [The Odin Project](https://www.theodinproject.com/) however provides the user with an action to mark the chapter as complete.

![Screenshot 2021-05-31 at 2 36 11 PM](https://user-images.githubusercontent.com/31363128/120172800-08a9ff00-c221-11eb-8e49-d64dee8ac29a.png)

After marking the chapter as Complete the user can change the status to Incomplete as well. This would ensure that if the user had by mistake marked the chapter as complete they can undo it.

![Screenshot 2021-05-31 at 2 37 08 PM](https://user-images.githubusercontent.com/31363128/120173001-38f19d80-c221-11eb-9571-d08c32d53e6d.png)

3. I personally liked the approach followed by The Odin Project. Would like to know your views.
4. Irrespective of the approach we take, the doctype to store the progress would be the same.

1. Name -  LMS Course Progress?
2. Fields
 - Course
 - Lesson
 - User
 - Status (Complete, Incomplete)

cc - @anandology

**Comment by pateljannat** [comment]
As discussed,
- Lessons have textual content, exercises, and quizzes.
- If a lesson only has textual content then it would be marked as complete on visitation itself.
- If a lesson has textual content + exercises or quizzes, then it would be marked as Partially Complete if the quizzes and exercises are not complete.
- So to complete such lessons a student must perform all exercises and quizzes as well.
