### ISSUE TITLE
As a student, I should be able to view a list of all courses

### ISSUE THREAD

**Issue by v-pai** [fossunited/community#119]
### Problem
Students can view a list of courses but we want to add more details to this page to aid the browsing process.

### Proposed solution
For the listing page, we want to show a list of courses and aid the student with some filtering abilities that might help them narrow down and view a list of courses based on their interest. On the listing page, a student should be able to:
- View a list of all active courses
- View a list of all upcoming courses

For each course a student should be able to view certain meta information that might help them make a decision about viewing more details of the course. For each course, a student should be able to:
- View a cover art for each course, so that each course is easily discernible
- View the name of the course
- View course creator's image and name
- View the difficulty level of the course
  - These difficulty levels are 'Beginner', 'Intermediate', and 'Advanced'
- View any reviews and feedback for the course left by older students of that course (not sure about this feature but noting it down for now)

---

- Additionally, these are some points we could include based on feedback
  - Number of lessons
  - (Rough) estimate of the time required to finish the course
  - Filter courses based on availability, topic, and difficulty-level
    - We can add more filter options if necessary but these seem good for the first cut

~~- View the progress on the number of students that have signed up and the number of slots left~~
    ~~- this helps to give an idea of how much time a student has to evaluate the course and sign up~~
~~- Have a 'View Course' button?~~
  ~~- I am a little split about this, the entire card could be clickable without having the need to show a 'view course' button~~
  ~~- The reason we may need a 'View Course' button is if we decide to make the creator's/mentor's name and image clickable we'll have to redirect them to a list showing all the courses created by that creator/mentor~~

**Comment by anandology** [comment]
Filtering is useful where are more courses than that can be seen in a single screen. While I agree that it is a useful feature, given that both mon school and frappe school are going to have only handful of courses, I suggest to not include filtering in the current iteration.

**Comment by v-pai** [comment]
@anandology Okay. I wasn't sure of how many courses we may have and how early we may be into this feature so I added it to the list. I've edited the issue description and moved it all the way to the bottom as a part of 'additional' features we can include based on feedback

**Comment by anandology** [comment]
How about this requirement?

As a student, I want to find out how long does it take to complete this course.

If it is a video course, how long the videos are (something like 4 hours). I'm not sure how to get to a number for courses that have exercises though. 

In any case, I think it is important to let the users have a sense how long the course would take to compelte. If not as number, we may have categories like micro-course, short-course and long-course etc. 

Thoughts?

**Comment by v-pai** [comment]
@anandology Is there a way for us to know how much time it takes for a student to finish a course or is this a guesstimate? I think with courses that aren't mentor driven this may be easier to do. But a course with mentors might take longer since there's a dependency on the mentor as well.

How about we show the number of lessons in each course instead of the time? Maybe the time can be added once we have more people taking a course.

**Comment by v-pai** [comment]
Updated the spec

- removed the 'progress on enrolments' since students can take a course without having to sign up for a batch
- removed making the creator's name and image clickable
   - this will be visible in the 'Course Details' page
   - removing this also ensure we don't need to a separate 'View Course' button
