### ISSUE TITLE
As a student, I want to explore the content of a particular course

### ISSUE THREAD

**Issue by v-pai** [fossunited/community#126]
### Problem
Student should be able to view all the details of a course on its 'home' page.

### Considerations
On the course home, a student should be able to view the following:

- Course title
- Course description
- Course difficulty level
- Video preview of the course, if there is one
- A Call-To-Action to enrol for a batch [1]
- Course content [2]
- Detailed information about the course creator
- List of batches [3]
- Learnings from this course: What will the student learn if they finish this course
- Any pre-requisites about the course: Should the students know any other topic before taking this course [4]
- FAQs (Why take the course)
- FAQs (general)
- Student reviews of the course

---

[1]
- Enrolment interaction is not a part of this user story

[2] 
Should be a list of lessons and topics covered within those lessons. We could also show the average time taken to finish a lesson. 

[3]
A batch will have the following information
- Batch number
- A date range in which the batch runs 
- Days on which a batch runs, ex: Every Monday and Tuesday
- Timings of the batch
- How full the batch is / How many slots left

[3]
Does the LMS have another course on the topic that students need to know? If yes, we should show that course as well

**Comment by pateljannat** [comment]
> * Batch number

Batch Title is what we are using currently. 

Rest looks good to me.

For the batches we are also displaying the days on which the batch sessions will be conducted.

Like,

Session on every Monday

or

Sessions on Saturday, Sunday

This might help users chose batch based on their schedule. Some may prefer weekdays, other may prefer weekend.

**Comment by v-pai** [comment]
@pateljannat I've added this to the batches section.
