### ISSUE TITLE
Desciption of the courses has shift to the left

### ISSUE THREAD

**Issue by wisharya** [fossunited/community#13]
The description of the courses seems to shift to the left. Please look into this.

![Screenshot_2021-04-03 Course](https://user-images.githubusercontent.com/25725389/113473899-0e39d180-948a-11eb-92fb-70051c2b3b6a.png)

**Comment by pateljannat** [comment]
Seems fine on my side

![Screenshot 2021-04-07 at 11 19 29 AM](https://user-images.githubusercontent.com/31363128/113860463-b53ca700-97c3-11eb-89aa-6c3548a1e6cc.png)

**Comment by wisharya** [comment]
Ah, Seem fine to me as well now -_-
