### ISSUE TITLE
Learning Modes

### ISSUE THREAD

**Issue by pateljannat** [fossunited/community#130]
1. LMS Course will have a field called Learning Mode. This will be a select field with the following options

- Self Learning
- Mentor Based Learning

2. For Mentor Based Learning everything will work as it is currently.
3. For Self Learning, a batch will be created automatically for the course and all students opting for this course would become a member of this batch.

**Queries:**
1. Should we allow the course creator to change the Learning mode after the course is created or should this be a set-only-once option?

cc: @rmehta @anandology

**Comment by rmehta** [comment]
My thoughts:

1. Every course must be available for self learning
2. A mentor can pick any course for mentoring

So

1. A mentor can pick a course -> start a batch
1. On the course home page, if there is a batch starting, it will be displayed (or not)?

So learning modes become redundant?
