### ISSUE TITLE
Batch Progress is showing exercises in the wrong order

### ISSUE THREAD

**Issue by anandology** [fossunited/community#135]
**Describe the bug**
The Batch Progress page is showing the exercises as:

* Exercise 1.1
* Exercise 1.10
* Exercise 1.11
* Exercise 1.12
* Exercise 1.2
* Exercise 1.3
* etc.

This is happening because of the sorting.

**To Reproduce**
1. visit any progress page of any batch with course having more than 10 exercises in a chapter

**Comment by pateljannat** [comment]
@anandology can we close this now that we don't have a progress tab?

**Comment by anandology** [comment]
Yes, closing this issue.
