### ISSUE TITLE
when multiplication symbol(*) used written code is splitting into two and given figures   are not mentioned.

### ISSUE THREAD

**Issue by ajju2003** [fossunited/community#150]
**Describe the bug**
In (staging.mon.school) website" Written code is splitting into two parts when we use multiplication symbol(*) and reload it after submitting the exercises"  and in chapter(positioning shapes) "given below" figures  are not mentioned . these are the two bugs found.

**To Reproduce**
1. Go to 'staging.mon.school 'website
2. Click on '.chapter(NUMBERS). ..'
3. Scroll down to '..FACTORIAL OF 5 problem..'
5. after completing the problem and submit it and reload it 

**Expected behavior**
I expect ,when i use multiplication symbol the code should not get split into two 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/87330000/125395028-39f11f80-e3c8-11eb-80c8-7c2c9618a04f.PNG)

**Desktop (please complete the following information):**
 -chrome
 - Version []

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ajju2003** [comment]
![Capture 2](https://user-images.githubusercontent.com/87330000/125396459-352d6b00-e3ca-11eb-8d93-afc01a3720a2.PNG)

**Comment by ajju2003** [comment]
there is no figures  mentioned here this is also a bug

**Comment by anandology** [comment]
Fixed.
