### ISSUE TITLE
Issue List - [August]

### ISSUE THREAD

**Issue by pateljannat** [fossunited/community#178]
The issue mentioned here would be fixed in August's Bugfix sprint.

- [x] Course Outline drawer icon animation on click is not working properly
- [x] When a course is marked as an upcoming course the Start Learning button shouldn't appear
- [x] Author field in LMS Course doctype
- [x] Make chapter description Small Text
- [x] On the Course page the chapter description and Lesson Title are looking almost the same.
- [x] Lessons should be visible to course creators without joining the course.
- [x] Improve UI for discussion message when the user is not logged in
- [x] Markdown extension for non-youtube video
- [x] Create a new lesson and add a quiz to it. It throws an error on the lesson name.
- [x] Empty overview section on the profile page.
- [x] Modern design for certificate page.
- [x] UI Cleanup
- [x] Hide summary button from quiz if a user is not logged in or user is not a member of the course.
- [x] Empty state for reviews
- [x] UI for notify me button
- [x] Remove Course Mockup files.

**Comment by v-pai** [comment]
# Here are some changes for the UI cleanup

### For 'all course' page
Some of the changes mentioned for this page, applies across all pages
```
body {
	background: #F4F5F6;
}

.common-page-style {
	padding-bottom: 5rem;
}

.container {
	margin-top: 3rem;
}

.courses-header {
	margin-bottom: 1.5rem;
	padding: 0 1rem;
}

.cards-parent {
	grid-template-columns: repeat(auto-fill,minmax(300px,1fr));
	column-gap: 40px;
	row-gap: 40px;
}

.common-card-style {
	box-shadow: 0 0px 4px 2px #19273405;
/*
- reduced intensity of box shadow
- the TOC doesn't have a box shadow, we should add it to all cards
*/
}

.course-tags {
	top: 1rem;
	left: 1rem;
}

.web-footer {
	background: #FFF;
}
```

---

### For the course home

```
.breadcrumb {
	padding: 0 1rem;
}

.course-card-wide {
	border-radius: 8px;
/*
- border radius 8px everything
- the designs have border radius at 12, but we should keep it at 8
- our border radius is inconsistent across cards
*/
}

.description-card {
	p {
		font-size: 1rem;
		line-height: 1.72;
		
		&:last-child {
			margin-bottom: 0;
		}
}

.course-home-headings {
	padding: 0 1rem;
}

.coure-outline { 
// course is misspelled
	border-radius: 8px;
	box-shadow: 0 0px 4px 2px #19273405;
}
```

---

### Semantics

![Headings in divs](https://user-images.githubusercontent.com/81136551/130662973-3e18f4b8-4d3a-434c-9a05-5aba1927d5de.png)

- 'Course Description' heading is in a div but 'Reviews' heading is in a span
- Headings should be h1 - h6 tags. These particular headings should be h3
---

### For the course details page

```
.discussion-on-page textarea.form-control {
	padding: 1rem;
}

.common-card-style.lesson-content-card {
	padding: 1rem;
	
	p {
		font-size: 1rem;
		line-height: 1.72;
		
		&:last-child {
			margin-bottom: 0;
		}
	}
}
```

---

### For Course Outline

```
.lessons {
	~~margin-bottom: 1rem;~~
}

.course-content-parent .lesson-links {
	~~line-height: 200%;~~
	margin-bottom: 4px;
}
```

---

### Reviews

- [ ] Need an empty state for reviews

---

I have more changes but it's getting harder to work on it in the inspect mode, I can suggest more changes once we push these out
