### ISSUE TITLE
RFC: User Profile

### ISSUE THREAD

**Issue by pateljannat** [fossunited/community#2]
Requirements:

1. A user can sign up by entering the following details:
- Full Name
- Email
- Username

2. The username field will have the following constraints.

it must have at least 4 characters
the username is case insensitive and will always be stored in lowercase
it can only have characters in the range [a-z0-9-]

3. A page to display the user's profile information.

**Comment by anandology** [comment]
Hey @ pateljannat , I took the libery to put your email here to move the discussion here.

```
I think we should not use the User Doctype and instead keep the Community Member doctype (or a doctype specific to the Course members, for now, I am assuming Community Member). The User doctype belongs to the frappe app and not the Community App. So any customizations that we make for it will reflect in the Frappe app and not the community. That won't be ideal. 

I have outlined a workflow for the course user setup. It involves creating a User for the members as well. But the primary source of information should be the Community Member doctype.

The workflow:
1. We will have a web form that will be based on the Community Member doctype.
2. It will have all the necessary fields including Username, Full Name, and email. This will solve the issue of asking username during sign-up.
3. When the user submits this form, the data will be saved in the Community Member doctype. A script will then create a User document for this member.
4. An email will be sent to these users to set their passwords. 
5. They can then log in with their email id and password but they won't have desk access. We can think of a role for them. They will be redirected to a page of our choice (User Profile Page).
6. For the User Profile page, we can enable web view for the Community Member doctype and that will be the user profile page.

Please let me know your thoughts on it.
```

**Comment by anandology** [comment]
I'm worried about the data being  duplicated across two doctypes. That doesn't sound like a good approach. 

How about having a CommunityMember/Profile doctype that somehow references the user and have the remaining fields in it. Would it be possible?

**Comment by anandology** [comment]
> Requirements:
> 
>     1. A user can log in by entering the following details:
> 
> 
>     * Full Name
> 
>     * Email
> 
>     * Username

Shouldn't it be sign up instead of login?

**Comment by pateljannat** [comment]
> Shouldn't it be sign up instead of login?

Yes right, I have made the correction.

**Comment by pateljannat** [comment]
> How about having a CommunityMember/Profile doctype that somehow references the user and have the remaining fields in it. Would it be possible?

The data that the user enters in the web form would be saved as the profile and also in the user doctype, ensuring that for a user, data remains the same throughout. So picking data from Community Member doctype won’t cause any issues IMO.
