### ISSUE TITLE
Adding chapter to courses pop-ups chapter doctype from Non profit module (not from community app)

### ISSUE THREAD

**Issue by wisharya** [fossunited/community#212]
While adding chapters in a course (through Quick Entry) pop-ups chapter doctype from the Non-profit module, not the LMS chapter module.
P.S. -  I have installed Frappe Framework + ERPNext + Community apps to the site, unlike Mon.School (Framework + Community app only)

![Screenshot from 2021-09-27 18-22-10](https://user-images.githubusercontent.com/25725389/134911631-57e4e9a5-01b7-483b-add8-213899a418a7.png)

**Comment by pateljannat** [comment]
https://github.com/fossunited/community/pull/216
