### ISSUE TITLE
Unable to apply as mentor

### ISSUE THREAD

**Issue by anandology** [fossunited/community#30]
## Describe the Bug

Clicking the "Apply Now" button in the mentor section is raising an error.

## How to Reproduce

1. Go to a course page
2. Click on 'Apply Now' in the mentor section
3. See the error popup

**Expected behavior**

A confirmation message should be shown.

**Screenshots**

<img width="1304" alt="Screenshot 2021-04-21 at 12 51 40 PM" src="https://user-images.githubusercontent.com/7569/115513404-a6182780-a2a0-11eb-9cdf-cf5c990930f9.png">

**Comment by pateljannat** [comment]
Fixed. Email templates have been used to notify members about their requests. Appropriate email templates can be selected in LMS Settings. The error occurred as there was no email template set in LMS Settings.

After the fix, a mentor request will be noted, but email will not be sent if the template is not present in LMS Settings.

**Comment by anandology** [comment]
Can't we define a  default email template?
