### ISSUE TITLE
Create mockup for sketches page

### ISSUE THREAD

**Issue by anandology** [fossunited/community#35]
The website will have a page to show case the recent skethes people have made.

First version of the page can be seen at:
https://dev.fossunited.org/sketches

Reimagine this page.

**Comment by anandology** [comment]
I've added a mockup with the existing styles. Keeping this issue open as there is a lot of room for improving it.

**Comment by anandology** [comment]
Let's do the mockup in figma.

**Comment by saviomartin** [comment]
Made a sketch on figma: [https://www.figma.com/file/TUr5V3TJHeVHPoUSc5lW7x/Foss-Untiked-Sketches-Page?node-id=0%3A1](https://www.figma.com/file/TUr5V3TJHeVHPoUSc5lW7x/Foss-Untiked-Sketches-Page?node-id=0%3A1)


![Desktop - 1](https://user-images.githubusercontent.com/61895712/116651568-1dd10b00-a9a1-11eb-87bd-0d895ca8482c.png)

**Comment by anandology** [comment]
Hi @saviomartin, thanks for making the mockup. I really like the footer of the sketch.

However, we are not going with the fossunited theme and the new theme is in the [Figma page of community project][1]. I've already invited you to that project. I don't think you've accepted it yet. Could you please check you email and see if you have the invite?

[1]: https://www.figma.com/file/WSqR0dBq3sTRntlCgsDw3s/Dashboard?node-id=400%3A243

**Comment by saviomartin** [comment]
Hi @anandology, I got it! I'm off to it!

**Comment by anandology** [comment]
On Fri, Apr 30, 2021 at 2:59 PM Savio Martin ***@***.***>
wrote:

> Hi @anandology <https://github.com/anandology>, I got it! I'm off to it!
>

Hey @savio, please ping me on telegram to coordinate.

**Comment by anandology** [comment]
done.
