### ISSUE TITLE
Is this MIT or AGPL licensed software?

### ISSUE THREAD

**Issue by wisharya** [fossunited/community#36]
@anandology 

I found two licences in this repo - MIT in file [licence.txt](https://github.com/fossunited/community/blob/main/license.txt) and AGPL in [README.md](https://github.com/fossunited/community/blob/main/README.md). 

Please look into this.

**Comment by anandology** [comment]
Thanks @wisharya  for bringing this to our notice. 

@pateljannat Looks like you've changed the license from MIT to AGPL in the commit 84cf74e25de62e634550a74729bfa29513d57b84. Any specific reason for making that change?

**Comment by pateljannat** [comment]
Rushabh suggested that we should use AGPL. I'll make the change in licence.txt as well
