### ISSUE TITLE
Invite and Login flow

### ISSUE THREAD

**Issue by pateljannat** [fossunited/community#42]
1. The website will not have a Sign-up option. It will only have Login.

2. When users come to the Landing Page  they will see a textbox for entering email before the "Request Invite"
  `  [Enter your email     ] [Request Invite]`

3. If the email is invalid or already used, it should show an error right there. Once the request is registered, the form will be replaced with a message "Thanks for your interest in Mon School. We have recorded your interest and we will get back to you shortly."

6. The information of this form will be saved in a doctype called **Invite Request**.

7. This doctype will have a status field. [Pending, Approved, Rejected, Registered].

8. When Admins change the status of the Request to Approved, these users will get another email. The email will have a link to a new signup form.

9. The NewSignup form will have the following fields.

 - Full Name
 - email
 - username
 - password
 - invite code
 
> Note: The invite code will be different for every user. We will be using the name of the document as the invite code.

10. After this form is submitted, the information will be stored back in the doctype **Invite Request** and a User will be created using this information.

>Please note that the signup email could be different from the invite email.  If the user uses a different email for signup it will be saved in a new field and the existing field will not be overridden.

**Comment by pateljannat** [comment]
@anandology Please review the flow and let me know if I missed something. Also, are the names of forms and doctypes okay?

**Comment by anandology** [comment]
> 3. When they click on it, they will be redirected to a form Request for Invitation.

I don't think I want to redirect to a different page. The Reqest invite should happen right on the page. There are two options.

Option 1: Add a textbox for email before the "request invite"

```
    [Enter your email     ] [Request Invite]
```

Option 2: Open a popup window and complete the invite process.

My preference is to go with option-1.

If the email is invalid or already used, it should show an error right there. Once the request is registered, the form will be replaced with a message "Thanks for your interest in Mon School. You'll recorded your interest and we will get back to you  shortly."

**Comment by anandology** [comment]
> 8. When Admins change the status of the Request to Approved, these users will get another email. This email will have a link to another form called Your Request has been Approved.
> 9. This form will ask for the basic information required to create a user in the app. [Full Name]

The email have a link to new signup form. 

The NewSignup form will have the following fields.

* Full Name
* email
* username
* password
* invite code

The invite code will be a query parameter and that will be autofilled. 

> 10. After this form is submitted, the information will be stored back in the doctype Request for Invitation and a User will be created using this information.

After the signup, the status of the "Request to Invitation" is changed to Complete and the username/email is added to that document for cross referene. Please note that the signup email could be different from the invite email.

> 11. When the User is created, the default welcome email will be sent to the user with a link to set the password.
> 12. The users can then set a password and log into the app.

No need of these to steps.

**Comment by anandology** [comment]
> This doctype will have a status field. [Pending, Approved, Rejected].
`[Pending, Approved, Registered, Rejected]`

The status is changed to Registred when the the user signs up using the invite link.

Can we call this doctype `InviteRequest` instead of `Request for Invite`?

**Comment by pateljannat** [comment]
> > 1. When they click on it, they will be redirected to a form Request for Invitation.
> 
> I don't think I want to redirect to a different page. The Reqest invite should happen right on the page. There are two options.
> 
> Option 1: Add a textbox for email before the "request invite"
> 
> ```
>     [Enter your email     ] [Request Invite]
> ```
> 
> Option 2: Open a popup window and complete the invite process.
> 
> My preference is to go with option-1.
> 
> If the email is invalid or already used, it should show an error right there. Once the request is registered, the form will be replaced with a message "Thanks for your interest in Mon School. You'll recorded your interest and we will get back to you shortly."

**Comment by pateljannat** [comment]
> My preference is to go with option-1.

Yes option 1 seems fine.


> The invite code will be a query parameter and that will be autofilled.

Will the invite code be the same for all the users or will it be unique. Also, we will need to have some sort of validations for the code as well. Maybe a doctype with all invite codes and the field that indicates if the code has been used or not?



> Please note that the signup email could be different from the invite email.

If the user uses a different email for signup do we override this in the doctype or save this in a new field?



> The status is changed to Registred when the the user signs up using the invite link.

You mentioned in the previous comment that the status changes to Complete.


> Can we call this doctype `InviteRequest` instead of `Request for Invite`?

Sure **Invite Request** is fine.

**Comment by anandology** [comment]
> > My preference is to go with option-1.
> 
> Yes option 1 seems fine.
> 
> > The invite code will be a query parameter and that will be autofilled.
> 
> Will the invite code be the same for all the users or will it be unique. Also, we will need to have some sort of validations for the code as well. Maybe a doctype with all invite codes and the field that indicates if the code has been used or not?

It will be different. 

I think we can use the name of the document as the invite code. 

> > Please note that the signup email could be different from the invite email.
> 
> If the user uses a different email for signup do we override this in the doctype or save this in a new field?

I think saving as a new field would be better.
 
> > The status is changed to Registred when the the user signs up using the invite link.
> 
> You mentioned in the previous comment that the status changes to Complete.

`Registered`. Updated that comment.

> 
> > Can we call this doctype `InviteRequest` instead of `Request for Invite`?
> 
> Sure **Invite Request** is fine.
👍🏽
