### ISSUE TITLE
Invite code get changed in Firefox

### ISSUE THREAD

**Issue by wisharya** [fossunited/community#83]
While following the invite link to create an account on Mon School, the invite code gets changed on the Firefox browser. Working fine on Chromium browsers.

![Screenshot(16)](https://user-images.githubusercontent.com/25725389/117470808-d46e5600-af74-11eb-9e29-72d8b5f57d4c.png)

**Comment by anandology** [comment]
We thought it was a caching issue. But looks like it is caused by text encoding used by the email. It replaces `=` with `=3D` and that seems to have interfered with the link. 

It seems to be working now.
