### ISSUE TITLE
Create a custom app for mon.school branding

### ISSUE THREAD

**Issue by rmehta** [fossunited/community#85]
Remove all mon.school branding from this app and move it to a custom app. This should be a vanilla app that can be used for any deployment.

**Comment by anandology** [comment]
Removed all the branding. We still have the home page that is still spefic to mon school.

**Comment by anandology** [comment]
Actually, the home page is quite generic. providing a way to customize the hero would be good enough.

**Comment by rmehta** [comment]
I think we should also remove the homepage - Website Templates are a good way to handle it.

**Comment by anandology** [comment]
How will you add recent courses and recent sketches?

**Comment by pateljannat** [comment]
@anandology can we close this now?

**Comment by anandology** [comment]
Yes, closed.
